record `i0.c$c` @kind class @AccessFlag  extends `java.util.concurrent.FutureTask` @kind class {
  `i0.c` `i0.c$c.g` @AccessFlag FINAL_SYNTHETIC;
}
procedure `void` `<init>`(`i0.c$c` v0 @kind this, `i0.c` v1 @kind object, `java.util.concurrent.Callable` v2 @kind object) @signature `Li0/c$c;.<init>:(Li0/c;Ljava/util/concurrent/Callable;)V` @AccessFlag CONSTRUCTOR {
    temp;

  #L50ec04.  v0.`i0.c$c.g` @type ^`i0.c` := v1 @kind object;
  #L50ec08.  call `<init>`(v0, v2) @signature `Ljava/util/concurrent/FutureTask;.<init>:(Ljava/util/concurrent/Callable;)V` @kind direct;
  #L50ec0e.  return @kind void;
}
procedure `void` `done`(`i0.c$c` v3 @kind this) @signature `Li0/c$c;.done:()V` @AccessFlag PROTECTED {
    temp;
    v0;
    v1;
    v2;

  #L50ec20.  v0:= "An error occurred while executing doInBackground()" @kind object;
  #L50ec24.  call temp:= `get`(v3) @signature `Ljava/util/concurrent/FutureTask;.get:()Ljava/lang/Object;` @kind virtual;
  #L50ec2a.  v1:= temp @kind object;
  #L50ec2c.  v2:= v3.`i0.c$c.g` @type ^`i0.c` @kind object;
  #L50ec30.  call `m`(v2, v1) @signature `Li0/c;.m:(Ljava/lang/Object;)V` @kind virtual;
  #L50ec36.  goto L50ec6a;
  #L50ec38.  v1:= Exception @type ^`java.lang.Throwable` @kind object;
  #L50ec3a.  v2:= new `java.lang.RuntimeException`;
  #L50ec3e.  call `<init>`(v2, v0, v1) @signature `Ljava/lang/RuntimeException;.<init>:(Ljava/lang/String;Ljava/lang/Throwable;)V` @kind direct;
  #L50ec44.  throw v2;
  #L50ec46.  v0:= v3.`i0.c$c.g` @type ^`i0.c` @kind object;
  #L50ec4a.  v1:= 0I;
  #L50ec4c.  call `m`(v0, v1) @signature `Li0/c;.m:(Ljava/lang/Object;)V` @kind virtual;
  #L50ec52.  goto L50ec6a;
  #L50ec54.  v1:= Exception @type ^`java.util.concurrent.ExecutionException` @kind object;
  #L50ec56.  v2:= new `java.lang.RuntimeException`;
  #L50ec5a.  call temp:= `getCause`(v1) @signature `Ljava/util/concurrent/ExecutionException;.getCause:()Ljava/lang/Throwable;` @kind virtual;
  #L50ec60.  v1:= temp @kind object;
  #L50ec62.  call `<init>`(v2, v0, v1) @signature `Ljava/lang/RuntimeException;.<init>:(Ljava/lang/String;Ljava/lang/Throwable;)V` @kind direct;
  #L50ec68.  throw v2;
  #L50ec6a.  return @kind void;
  catch `java.lang.InterruptedException` @[L50ec24..L50ec36] goto L50ec6a;
  catch `java.util.concurrent.ExecutionException` @[L50ec24..L50ec36] goto L50ec54;
  catch `java.util.concurrent.CancellationException` @[L50ec24..L50ec36] goto L50ec46;
  catch `java.lang.Throwable` @[L50ec24..L50ec36] goto L50ec38;
}
