record `kotlinx.coroutines.t1` @kind class @AccessFlag PUBLIC_ABSTRACT {
}
procedure `java.lang.Object` `a`(`kotlin.coroutines.CoroutineContext` v0 @kind object, `kotlin.jvm.functions.Function0` v1 @kind object) @signature `Lkotlinx/coroutines/t1;.a:(Lkotlin/coroutines/CoroutineContext;Lkotlin/jvm/functions/Function0;)Ljava/lang/Object;` @AccessFlag PUBLIC_STATIC_FINAL_SYNTHETIC {
    temp;

  #L2cef64.  call temp:= `b`(v0, v1) @signature `Lkotlinx/coroutines/t1;.b:(Lkotlin/coroutines/CoroutineContext;Lkotlin/jvm/functions/Function0;)Ljava/lang/Object;` @kind static;
  #L2cef6a.  v0:= temp @kind object;
  #L2cef6c.  return v0 @kind object;
}
procedure `java.lang.Object` `b`(`kotlin.coroutines.CoroutineContext` v1 @kind object, `kotlin.jvm.functions.Function0` v2 @kind object) @signature `Lkotlinx/coroutines/t1;.b:(Lkotlin/coroutines/CoroutineContext;Lkotlin/jvm/functions/Function0;)Ljava/lang/Object;` @AccessFlag PRIVATE_STATIC_FINAL {
    temp;
    v0;

  #L2cef80.  v0:= new `kotlinx.coroutines.b3`;
  #L2cef84.  call temp:= `i`(v1) @signature `Lkotlinx/coroutines/c2;.i:(Lkotlin/coroutines/CoroutineContext;)Lkotlinx/coroutines/z1;` @kind static;
  #L2cef8a.  v1:= temp @kind object;
  #L2cef8c.  call `<init>`(v0, v1) @signature `Lkotlinx/coroutines/b3;.<init>:(Lkotlinx/coroutines/z1;)V` @kind direct;
  #L2cef92.  call `d`(v0) @signature `Lkotlinx/coroutines/b3;.d:()V` @kind virtual;
  #L2cef98.  call temp:= `invoke`(v2) @signature `Lkotlin/jvm/functions/Function0;.invoke:()Ljava/lang/Object;` @kind interface;
  #L2cef9e.  v1:= temp @kind object;
  #L2cefa0.  call `a`(v0) @signature `Lkotlinx/coroutines/b3;.a:()V` @kind virtual;
  #L2cefa6.  return v1 @kind object;
  #L2cefa8.  v1:= Exception @type ^`java.lang.Throwable` @kind object;
  #L2cefaa.  call `a`(v0) @signature `Lkotlinx/coroutines/b3;.a:()V` @kind virtual;
  #L2cefb0.  throw v1;
  #L2cefb2.  v1:= Exception @type ^`java.lang.InterruptedException` @kind object;
  #L2cefb4.  v2:= new `java.util.concurrent.CancellationException`;
  #L2cefb8.  v0:= "Blocking call was interrupted due to parent cancellation" @kind object;
  #L2cefbc.  call `<init>`(v2, v0) @signature `Ljava/util/concurrent/CancellationException;.<init>:(Ljava/lang/String;)V` @kind direct;
  #L2cefc2.  call temp:= `initCause`(v2, v1) @signature `Ljava/util/concurrent/CancellationException;.initCause:(Ljava/lang/Throwable;)Ljava/lang/Throwable;` @kind virtual;
  #L2cefc8.  v1:= temp @kind object;
  #L2cefca.  throw v1;
  catch `java.lang.InterruptedException` @[L2cef80..L2cef98] goto L2cefb2;
  catch `java.lang.Throwable` @[L2cef98..L2cefa0] goto L2cefa8;
  catch `java.lang.InterruptedException` @[L2cefa0..L2cefb2] goto L2cefb2;
}
